# Generated by Django 5.0.8 on 2024-08-18 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0003_alter_homesection_sub_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='homesection',
            name='image',
            field=models.ImageField(blank=True, default='image/', null=True, upload_to='testapp/'),
        ),
    ]
