# Generated by Django 5.0.8 on 2024-08-18 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0004_homesection_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homesection',
            name='type_choices',
            field=models.CharField(choices=[('HERO', 'hero'), ('ABOUT', 'about'), ('PROJECT', 'project'), ('CLIENT', 'client'), ('ASK-PROJECT', 'ask-project')], default='HERO', max_length=15),
        ),
    ]
