# Generated by Django 5.1 on 2024-08-18 09:00

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0005_alter_homesection_type_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homesection',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
