# Generated by Django 5.1 on 2024-08-18 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0007_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='tag',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
