# Generated by Django 5.1 on 2024-08-18 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0008_item_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='item',
            name='tag',
        ),
        migrations.AddField(
            model_name='item',
            name='blog_tag',
            field=models.ManyToManyField(to='testapp.blogtag'),
        ),
    ]
