# Generated by Django 5.1 on 2024-08-18 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0009_blogtag_remove_item_tag_item_blog_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='media',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
